### ISSUE TITLE
Styling inconsistent with built-in studio plugins

### ISSUE THREAD

**Issue by pinehappi** [SpaceDice9/exestack#3]
The colors for the search bar and top header are reversed of what they are in the built-in Studio plugins for dark mode.

![colors](https://github.com/user-attachments/assets/d65cbdc1-bdc6-48aa-a67a-7966230f8f09)

Additionally, the styling for selected elements is not consistent with the styling for selected elements in other parts of the studio UI like the explorer. It is also difficult to differentiate what is a folder/byt/snippet because the icons are all the same color and blend together.

![selection](https://github.com/user-attachments/assets/d87de3a0-7324-4082-8c0b-d1967324f397)

## Suggested Solution
Change the colors for the top header to match the one in the built-in Studio plugins.

Change the styling for elements to match that of the explorer (remove the stroke, have only background and text color change). Have icons be colored even when not selected to help differentiate them.

If you want to go through with these changes, I can create a pull request for them.

**Comment by SpaceDice9** [comment]
I would not change the colors for the header because there is no benefit to it besides consistency, which isn't a priority at the moment. The element styling is a good UX change, so I would go for that.

**Comment by SpaceDice9** [comment]
Merged with https://github.com/SpaceDice9/exestack/commit/86ff9123de944f36dd58b29e0e2752e2a7137542
